project_id = "lanbort"

[api]
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
major_version = 15

[db.migrations]
enabled = true

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://127.0.0.1:3000/**", "http://localhost:3000/**"]

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[storage]
enabled = true

[experimental.pgdelta]
enabled = true
